apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-demo-html
  namespace: gitops-demo
data:
  index.html: |
    <html>
      <body style="font-family: sans-serif; text-align:center; margin-top:100px;">
        <h1>GitOps demo on Raspberry Pi k3s</h1>
        <p>Deployed and synced by ArgoCD</p>
      </body>
    </html>