apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-bot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DOHOON0127/HomeServer-Infra-Bot.git
    targetRevision: main
    path: k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-bot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
